apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: dev-namespace
spec:
  accessModes:
  - ReadWriteOnce
  resources: 
    requests:
      storage: 2Gi
  storageClassName: default