# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
  namespace: dev-namespace
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: "411b27c4-15d9-40c5-a0c9-2bf7d6b0dccb"   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: "saurabhaks"        # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: db-host
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: db-name
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""  
        - |
          objectName: db-password
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""  
        - |
          objectName: db-user
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""  
    tenantId: "b351153d-27b5-41c9-974e-6f582023699d"            # The tenant ID of the key vault
  secretObjects:
  - secretName: backend-secrets
    type: Opaque
    data:
    - objectName: db-host
      key: DB_HOST
    - objectName: db-name
      key: DB_NAME
    - objectName: db-password
      key: DB_PASSWORD
    - objectName: db-user
      key: DB_USER